name: 🕳️ Сообщить о провале
description: Добавить новый карстовый провал на карту
title: "[Провал] "
labels: ["new-sinkhole", "needs-verification"]
body:
  - type: markdown
    attributes:
      value: |
        ## Спасибо за вклад в карту!
        После проверки провал будет добавлен на карту.
        
  - type: input
    id: location
    attributes:
      label: 📍 Адрес / Местоположение
      description: Укажите адрес или опишите местоположение
      placeholder: "ул. Ленина, 25 / рядом с ТЦ Мега"
    validations:
      required: true
      
  - type: input
    id: coordinates
    attributes:
      label: 🌐 Координаты
      description: Если знаете (можно скопировать из Google Maps)
      placeholder: "54.7355, 55.9910"
      
  - type: input
    id: date
    attributes:
      label: 📅 Дата образования
      description: Когда образовался провал (примерно)
      placeholder: "Декабрь 2024 / Точная дата неизвестна"
      
  - type: textarea
    id: description
    attributes:
      label: 📝 Описание
      description: Размер, глубина, что произошло, последствия
      placeholder: |
        Размер примерно 2x3 метра, глубина около 1.5 м
        Образовался после дождей
        Огорожен забором
        
  - type: textarea
    id: photos
    attributes:
      label: 📷 Фотографии
      description: Перетащите фото сюда (drag & drop) или вставьте ссылки
      placeholder: "Перетащите файлы сюда"
      
  - type: dropdown
    id: type
    attributes:
      label: 🏷️ Тип
      description: Если знаете причину образования
      options:
        - Не знаю
        - Карстовый (природный)
        - Техногенный (авария на коммуникациях)
        - Другое
        
  - type: input
    id: source
    attributes:
      label: 📰 Источник информации
      description: Откуда вы узнали о провале
      placeholder: "Личное наблюдение / Новости / СМИ"

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Согласие
      options:
        - label: Подтверждаю достоверность информации
          required: true
        - label: Согласен на публикацию под лицензией CC BY 4.0
          required: true
